name: Rust
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: |
          case ${{ matrix.group }} in
            1) cargo test --test anime;;
            2) cargo test --test character;;
            3) cargo test --test manga;;
            4) cargo test --test people;;
            5) cargo test --test producer;;
            6) cargo test --test magazines;;
            7) cargo test --test watch;;
            8) cargo test --test seasons;;
            9) cargo test --test schedule;;
            10) cargo test --test clubs;;
            11) cargo test --test genre;;
            12) cargo test --test random;;
            13) cargo test --test top;;
            14) cargo test --test users;;
            15) cargo test --test review;;
            16) cargo test --test recommendations;;
          esac 
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -- -D warnings
